package rsInstanceJumpstart;

/*
 *     This file is part of rs-instance-jumpstart.
 *
 *  rs-instance-jumpstart is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  rs-instance-jumpstart is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with rs-instance-jumpstart.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright 2012, Daniel Emmons
 */
/**
 *
 * @author Daniel Emmons
 */
public class RSInstanceJumpstartMainForm extends javax.swing.JFrame {

    /**
     * Creates new form StartupPanelMainForm
     */
    public RSInstanceJumpstartMainForm() {
        initComponents();
        jPanelServers.setVisible(false);
        jPanelConnect.setVisible(true);
        currentRackspaceAccount = new rackspaceAccount();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelServers = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelCloudServersPane = new javax.swing.JPanel();
        jPanelConnect = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textFieldUsername = new java.awt.TextField();
        textFieldpassword = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("response");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        org.jdesktop.layout.GroupLayout jPanelCloudServersPaneLayout = new org.jdesktop.layout.GroupLayout(jPanelCloudServersPane);
        jPanelCloudServersPane.setLayout(jPanelCloudServersPaneLayout);
        jPanelCloudServersPaneLayout.setHorizontalGroup(
            jPanelCloudServersPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 854, Short.MAX_VALUE)
        );
        jPanelCloudServersPaneLayout.setVerticalGroup(
            jPanelCloudServersPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 236, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelCloudServersPane);

        org.jdesktop.layout.GroupLayout jPanelServersLayout = new org.jdesktop.layout.GroupLayout(jPanelServers);
        jPanelServers.setLayout(jPanelServersLayout);
        jPanelServersLayout.setHorizontalGroup(
            jPanelServersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelServersLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelServersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelServersLayout.setVerticalGroup(
            jPanelServersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelServersLayout.createSequentialGroup()
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("To connect to your account, you'll need your");

        jLabel2.setText("Rackspace username and API key.");

        jLabel3.setText("Username:");

        jLabel4.setText("API Key:");

        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsernameActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelConnectLayout = new org.jdesktop.layout.GroupLayout(jPanelConnect);
        jPanelConnect.setLayout(jPanelConnectLayout);
        jPanelConnectLayout.setHorizontalGroup(
            jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelConnectLayout.createSequentialGroup()
                        .add(jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(46, 46, 46)
                        .add(jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jButton1)
                            .add(textFieldUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(textFieldpassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                        .add(0, 363, Short.MAX_VALUE))
                    .add(jPanelConnectLayout.createSequentialGroup()
                        .add(jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(103, 103, 103))))
        );
        jPanelConnectLayout.setVerticalGroup(
            jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .add(33, 33, 33)
                .add(jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(textFieldUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel4)
                    .add(textFieldpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jMenu1.setText("Accounts");

        jMenuItem1.setText("Log In");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jPanelServers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jPanelServers, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //cloudServerPanels = new CloudServerPanelInstance [100];
        currentRackspaceAccount.initiateConnection(textFieldUsername.getText(), textFieldpassword.getText());
        jPanelConnect.setVisible(false);
        jPanelServers.setVisible(true);
        jMenuItem1.setText("Log in again (start over)");
        if (currentRackspaceAccount.getResponseCode() > 204) {
            jLabel5.setText("Failed to log in. Check Username, API Key, and internet connection.");
        } else {

            jLabel5.setText("Login successful, ");

            int i = 0;
            cloudServerPanels = new CloudServerPanelInstance[100];
            
            jPanelCloudServersPane.setLayout(new javax.swing.BoxLayout(jPanelCloudServersPane, javax.swing.BoxLayout.PAGE_AXIS));

            while (currentRackspaceAccount.getServerList()[i][0] != null) {
                 cloudServerPanels[i] = new CloudServerPanelInstance();
                 cloudServerPanels[i].initialize();
                 cloudServerPanels[i].setValues(
                 currentRackspaceAccount.getServerList()[i][0],
                 currentRackspaceAccount.getServerList()[i][1],
                 currentRackspaceAccount.getServerList()[i][2],
                 currentRackspaceAccount.getServerList()[i][3],
                 currentRackspaceAccount.getServerList()[i][4],
                 currentRackspaceAccount.getAuthToken()
                 );

                 jPanelCloudServersPane.add(cloudServerPanels[i].jPanelCloudServer);
                 cloudServerPanels[i].jPanelCloudServer.validate();
                 cloudServerPanels[i].jPanelCloudServer.setVisible(true);

                 jPanelCloudServersPane.add(cloudServerPanels[i].jPanelCloudServer);
                 i++;
            }
            
            jPanelCloudServersPane.revalidate();
            jLabel5.setText(jLabel5.getText() + String.valueOf(i) + " Servers in Shutoff state found.");
            //jPanelCloudServersPane.setVisible(true);

            //jLabel5.setText(currentRackspaceAccount.getServerList());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonsActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println(evt.getActionCommand());
        //power on the system, then disable button
        currentRackspaceAccount.powerOnServer(evt.getActionCommand());
        ((javax.swing.JButton)evt.getSource()).setEnabled(false);


    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if("Log in again (start over)".equals(jMenuItem1.getText())){
            jPanelServers.setVisible(false);
            jPanelCloudServersPane.removeAll();
            
            jPanelConnect.setVisible(true);
        } else {
        jPanelServers.setVisible(false);
        jPanelConnect.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void textFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSInstanceJumpstartMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSInstanceJumpstartMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSInstanceJumpstartMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSInstanceJumpstartMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSInstanceJumpstartMainForm().setVisible(true);


            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelCloudServersPane;
    private javax.swing.JPanel jPanelConnect;
    private javax.swing.JPanel jPanelServers;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField textFieldUsername;
    private java.awt.TextField textFieldpassword;
    // End of variables declaration//GEN-END:variables
    public rackspaceAccount currentRackspaceAccount;
    public CloudServerPanelInstance[] cloudServerPanels;
    
}
